import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import { StairTransition } from "@/components/StairTransition";
import localFont from 'next/font/local'

const jetbrains_mono = JetBrains_Mono({
  variable: "--font-jetbrains_mono",
  weight: ["100", "200", "300"],
  subsets: ["latin"],
  style: ["normal", "italic"]
});
const font_proxima_nova = localFont({
  variable: "--font-proxima-nova",
  style: "normal",
  src: [
    {
      path: './fonts/proximanova_black.otf',
      weight: '900',
      style: 'normal',
    },
    {
      path: './fonts/proximanova_bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/proximanova_light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/proximanova_regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
})
const font_brandon_grotesque = localFont({
  variable: "--font-brandon-grotesque",
  weight: "500",
  src: [
    {
      path: './fonts/Brandon_Grotesque_regular.otf'
    }
  ],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={(font_proxima_nova.variable, font_brandon_grotesque.variable)}
      >
        <Header />
        <StairTransition />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
