import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const fira_sans = Fira_Sans({
  variable: "--font-fira_sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  style: ["normal", "italic"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={(fira_sans.variable)}
      >
        {/* <StairTransition /> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
